### PR TITLE
WES refactor.

### PR DESCRIPTION
**Pull request by DailyDreaming**
I'm not sure if this is valuable or not, but I'm submitting back the changes I've made.  Feel free to reject it outright or cherry-pick, as I've made quite a few changes.

Many of these changes rely upon the current `workflow-service` PR here: https://github.com/common-workflow-language/workflow-service/pull/51  It uses this branch and some of the new functions within it for the wrapper.

I'm actively using this for monitoring and submitting workflows (using the latest WES schemas).

Changes:
- Lots of renaming
- Only 2 config files now, one for `toolregistries`/`workflowservices`/`evals` and one for the queued submissions.
- Additional params under evals to specify the workflow (this is likely to change, for my purposes at least, since the jsons currently there should be specified outside of this.  I only realized now that I'm actually running workflows).
- `monitor()` now recognizes if a server is not responding and displays appropriately.  It also now runs continuously (and is no longer recursive, because recursive calls are limited to 999 times in python (realistically this means it crashes after 16-20 minutes)).
- eliminated a number of utils that either could be called from `workflow-service` (or are already being leveraged) or didn't seem to fit.
- Made the travis testing more succinct and simplified the setup.

I haven't touched TRS or attempted to use `trs.client.py`.  The `run_checker()` function in `orchestrator.py` seemed to be the only function that leveraged this and I've commented it out.  I think this could be modified to allow it to run in the same way it did before, but I haven't had bandwidth to attempt to use TRS.

At the very least, I wanted to present changes in a way that could be cherry-picked, fully integrated, or rejected depending.  I'll probably continue to modify small portions for use in our current platform for a few weeks, but it does most of what we need it to for the time being.

I wanted to say too that I really liked the `monitor()` function and the display was pretty visually satisfying.  Thanks for creating this orchestrator!

### CODE REVIEW

**Comment by jaeddy** [comment]
Thanks, @DailyDreaming! Will be spending some quality time looking at these changes over the next couple days.

**Comment by DailyDreaming** [comment]
@jaeddy Sounds good!  I don't mind blunct criticism either if anything looks out of wack.  I know my particular needs atm may not quite be what this was intended for, but I hope you might be able to retrieve something useful out of it.

Also sorry, there are a number of additional changes now.  If you want a gauge of how I've been using this, the install process is something like:

INSTALLATION:
```
virtualenv venv && . venv/bin/activate

pip install toil[all]

git clone https://github.com/DailyDreaming/synapse-orchestrator.git
cd synapse-orchestrator
git checkout wes-refactor
pip install . --process-dependency-links && pip install -r dev-requirements.txt
cd ..

git clone https://github.com/common-workflow-language/workflow-service.git
cd workflow-service
git checkout symlinksNutil
pip install . --process-dependency-links && pip install -r dev-requirements.txt
cd ..
```

Write the config at `~/orchestrator_config.json`:
```
{
    "toolregistries": {
        "dockstore": {
            "host": "dockstore.org:8443", 
            "auth": "", 
            "proto": "https"
        }
    }, 
    "workflows": {
        "wdl_UoM_align": {
            "workflow_url": "tests/data/align.wdl", 
            "workflow_attachments": [], 
            "submission_type": "params", 
            "trs_id": "dockstore", 
            "version_id": "develop", 
            "workflow_type": "WDL"
        }, 
    }, 
    "workflowservices": {
        "local": {
            "auth_type": "", 
            "host": "0.0.0.0:8080", 
            "auth": "", 
            "proto": "http"
        }
    }
}
```

Then, activate the installation venv in 3 terminals:

Start the server in Terminal 1:
```(venv) $ wes-server --backend=wes_service.toil_wes --opt extra=--clean=never```

Load the orchestrator monitor in Terminal 2:
```(venv) $ orchestrate```

In Terminal 3, write a small script like:
```
from synorchestrator.orchestrator import set_queue_from_user_json, run_all

set_queue_from_user_json('tests/data/user_submission_example.json')
run_all()
```
 
 And run:
```(venv) $ python run_script.py```

**Comment by jaeddy** [comment]
OK — cherry-picked a bunch of commits, and I think I have most of the changes I want to pull in at the moment (holding off on bigger changes in e66d429 for now). Need to review and test a bit more locally, but lots of good stuff! I'll close this PR after confirming I haven't missed anything critical.

**Comment by DailyDreaming** [comment]
Sounds good, glad it was useful!

**Pull request closed without merging**
